version: '3'
services:
  db:
    image: postgres:11
    restart: always
    ports:
      - 32700:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: emoticon_generator
  dnmonster:
    image: amouat/dnmonster
    restart: always
    ports:
      - 5431:8080

